### ISSUE TITLE
Addon not working on the last stable OpenELEC release

### ISSUE THREAD

**Issue by cmvac** [emc02/hyp-rpi-oelec-jsonrpc-remote-addon#1]
@emc02: Hi and thanks for doing this addon, first of all. It is exactly what is missing on Hyperion. Unfortunately, it isn't working on my OpenELEC installation. It throws this error, according to the Kodi Log:

10:42:30  97.929359 T:1255797824  NOTICE: -->Python Interpreter Initialized<--
10:42:30  97.953690 T:1255797824   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.hyperioncontrol/hyperioncontrol.py", line 5, in <module>
                                                params=sys.argv[1]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

Any idea why and how to solve this? Thanks!

**Comment by cmvac** [comment]
One other thing: on OpenELEC with Hyperion installed, there is no Hyperion folder inside userdata. You have to make a new one, as well as a scripts one. Could it be that the scripts should be copied into the /storage/hyperion folder instead? 

I tested the scripts on the command line and they work. There must be something being missed here.

**Comment by emc02** [comment]
Hello!
Well I am using OpenELEC 6.0.3 and did a fresh install last week. For me all is working fine so far. I think you are the first one trying my Addon (except me) so I think there can be some problems. I will try to help you!
How did you call the hyperioncontrol.py? With SSH? The script need some arguments, that is what was missing in your case.
You have to call it with JSON-rpc commands to KODI like this:
http://kodiIP:Port/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Addons.ExecuteAddon" ,"params":{"addonid":"script.hyperioncontrol","params":{"cmd":"power_toggle"}}}

The hyperion folder in userdata has to be created. I've choosen this folder, because it can be accessed from network over SMB and so it's easier to change and add scripts.

**Comment by cmvac** [comment]
@emc02, hi, just got home from Mother's day, sorry for the late answer. I did not call hyperioncontrol.py, I just copied the content of the scripts onto the ssh command line. 

What do you mean with calling it with Json-rpc commands? Can you specify? Do you mean on the command line or inside Kodi? And if in Kodi, how?

**Comment by emc02** [comment]
The addon is for powering on and off a Relais that powers the leds for hyperion and for starting effects with json commands from kodi. You have to call the page
http://kodiIP:Port/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Addons.ExecuteAddon" ,"params":{"addonid":"script.hyperioncontrol","params":{"cmd":"power_toggle"}}}
from a browser within your Network. More Informationen and examples are in the readme.txt file.

**Comment by cmvac** [comment]
Ah, ok. I thought it could be used to "turn off" the leds by sending a black colour command, for example, or executing "killall hyperiond", for example. So you have a relay which powers the LEDs, but how do you command it through the addon? Is it connected to the GPIO? Let me take a look at the readme file. 

In theory, the addon and the scripts could be changed in order to operate the Hyperion setup without any Relay, right?

**Comment by emc02** [comment]
Yes, you can use it also without relay. I've connented one to a gpio port.
The command color_000000 will turn all leds to black.
http://kodiIP:Port/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Addons.ExecuteAddon" ,"params":{"addonid":"script.hyperioncontrol","params":{"cmd":"color_000000"}}}

There are all scripts possible, you just have to put them in the script folder and call them with the JSON_RPC command.

**Comment by cmvac** [comment]
Maybe I didn't explain myself right. The addon doesn't load at all, I tried to enter and I got an error. Hence the log message i wrote on top. I installed the addon by copying the folder into a script.hyperioncontrol.zip file, and then copying it into Kodi and installing as any other addon.

**Comment by cmvac** [comment]
This means I cannot even get to the other scripts your addon executes ;)

**Comment by emc02** [comment]
Ok, now I understand. Well, I also got problems with installing the zip file. I installed it with copying the addon directly to the addon path
Installation:
- copy the folder "script.hyperioncontrol" to "/storage/.kodi/addons/" on Raspberry Pi

with SSH: (copy folder script.hyperioncontrol e.g. with smb to downloads)
mkdir .kodi/addons/script.hyperioncontrol
cp downloads/script.hyperioncontrol/_._ .kodi/addons/script.hyperioncontrol

**Comment by emc02** [comment]
I think I have to rewrite the Installation procedure ;-)

**Comment by cmvac** [comment]
Yes, I guess so ;) 
 EDIT: Nevermind, I just read my own comment and realized it didn't make sense! :P

**Comment by cmvac** [comment]
Nope, still getting the same error. I'm on the same Openelec as you, so it shouldn't be an incompatibility.

**Comment by emc02** [comment]
Ok, so you get the error when you start the addon directly in Kodi?
The addon is not made to be run inside kodi directly. It can only be run from Browser with json-rpc commands. Maybe I will implement this Feature in future.

**Comment by cmvac** [comment]
Aha! That's why! Because that is exactly what I need! I want to then map a key on my remote to use it. You should specify that on the readme.txt file and also on the new Hyperion forum. But thanks for your help anyway. I've been using another self-made addon to turn it on/off and change between the ambilight sources, but yours sounded better :)

**Comment by emc02** [comment]
Thank you for your comments, I will make that more clear and/or add this features ;-)
I am controlling kodi only per http-json commands, that is why I made this addon. But maybe I can add some keymapping (when I have enough time)
